#include <stdio.h>
#include <unistd.h>
#include <sys/epoll.h>
#include <sys/wait.h>
#include <string.h>

int main(void)
{
    int pipefd[2];

    if (pipe(pipefd) < 0)
    {
        perror("pipe");
        return 1;
    }

    int epfd = epoll_create1(0);

    if (epfd < 0)
    {
        perror("epoll_create1");
        return 1;
    }

    struct epoll_event event;

    event.events = EPOLLIN;
    event.data.fd = pipefd[0];

    if (epoll_ctl(
        epfd,
        EPOLL_CTL_ADD,
        pipefd[0],
        &event
    ) < 0)
    {
        perror("epoll_ctl");
        return 1;
    }

    pid_t pid = fork();

    if (pid < 0)
    {
        perror("fork");
        return 1;
    }

    if (pid == 0)
    {
        close(pipefd[0]);

        sleep(1);

        const char* message =
            "Event generated by child";

        write(
            pipefd[1],
            message,
            strlen(message)
        );

        close(pipefd[1]);

        return 0;
    }

    close(pipefd[1]);

    printf("Parent waiting in epoll...\n");

    struct epoll_event events[4];

    int count = epoll_wait(
        epfd,
        events,
        4,
        -1
    );

    for (int i = 0; i < count; i++)
    {
        if (events[i].events & EPOLLIN)
        {
            char buffer[128];

            ssize_t bytes = read(
                events[i].data.fd,
                buffer,
                sizeof(buffer) - 1
            );

            if (bytes > 0)
            {
                buffer[bytes] = '\0';

                printf(
                    "Received: %s\n",
                    buffer
                );
            }
        }
    }

    waitpid(pid, NULL, 0);

    close(pipefd[0]);
    close(epfd);

    return 0;
}



